
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 18 02:25:19 CST 2018
//----------------------------------------------------

package AnalizadorCHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_CHEADER = 8;
  public static final int EQUALS = 2;
  public static final int T_FIMAGEN = 23;
  public static final int T_OPCION = 42;
  public static final int A_ID = 50;
  public static final int T_CCSS = 14;
  public static final int T_TEXTO = 20;
  public static final int T_ENLACE = 26;
  public static final int T_FILA = 30;
  public static final int A_ALTO = 52;
  public static final int T_SALTO = 46;
  public static final int T_CJS = 12;
  public static final int T_FCAJA = 41;
  public static final int T_FCHEAD = 33;
  public static final int A_RUTA = 47;
  public static final int T_FCELDA = 35;
  public static final int T_FCHEADER = 9;
  public static final int T_TEXTB = 38;
  public static final int T_BOTON = 24;
  public static final int T_TEXTA = 36;
  public static final int T_FCJS = 13;
  public static final int T_SPINNER = 44;
  public static final int A_ANCHO = 53;
  public static final int A_ALINEADO = 54;
  public static final int T_FPANEL = 19;
  public static final int A_TVALOR = 55;
  public static final int A_FONDO = 56;
  public static final int PYCOMA = 3;
  public static final int EOF = 0;
  public static final int T_CAJA = 40;
  public static final int T_FCHTML = 7;
  public static final int T_FTABLA = 29;
  public static final int T_FSPINNER = 45;
  public static final int error = 1;
  public static final int T_IMAGEN = 22;
  public static final int T_CHEAD = 32;
  public static final int T_CELDA = 34;
  public static final int T_CCUERPO = 10;
  public static final int A_GRUPO = 51;
  public static final int T_FTITLE = 17;
  public static final int T_PANEL = 18;
  public static final int T_FOPCION = 43;
  public static final int OTAG = 4;
  public static final int T_FENLACE = 27;
  public static final int T_FCCUERPO = 11;
  public static final int T_CHTML = 6;
  public static final int T_TABLA = 28;
  public static final int CTAG = 5;
  public static final int T_FTEXTO = 21;
  public static final int TEXTO_CHTML = 57;
  public static final int T_FCCSS = 15;
  public static final int T_FFILA = 31;
  public static final int A_VALOR = 49;
  public static final int A_CLICK = 48;
  public static final int T_FTEXTB = 39;
  public static final int T_FBOTON = 25;
  public static final int T_TITLE = 16;
  public static final int T_FTEXTA = 37;
}

