
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 19 15:41:55 CST 2018
//----------------------------------------------------

package AnalizadorCJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 33;
  public static final int CASO = 39;
  public static final int SI = 36;
  public static final int OBTENER = 51;
  public static final int RESTA = 14;
  public static final int PARAR = 11;
  public static final int MAYI = 26;
  public static final int MENS = 47;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int LISTO = 48;
  public static final int IGUAL = 21;
  public static final int SINO = 37;
  public static final int OR = 28;
  public static final int MIENTRAS = 42;
  public static final int MODU = 18;
  public static final int DEFEC = 40;
  public static final int DIV = 16;
  public static final int MENI = 25;
  public static final int SELECT = 38;
  public static final int SUMA = 13;
  public static final int ID = 3;
  public static final int OBSER = 53;
  public static final int SUSTRA = 20;
  public static final int PYCOMA = 4;
  public static final int EOF = 0;
  public static final int RETOR = 46;
  public static final int error = 1;
  public static final int TD_DATE = 9;
  public static final int COMA = 32;
  public static final int POTE = 17;
  public static final int SETEL = 52;
  public static final int DIF = 22;
  public static final int TD_BOOL = 7;
  public static final int TD_TEXTO = 6;
  public static final int DETENER = 43;
  public static final int TD_DATET = 10;
  public static final int ADDIC = 19;
  public static final int PUNTO = 34;
  public static final int FUNC = 45;
  public static final int MEN = 23;
  public static final int CLICK = 50;
  public static final int DPUNTO = 5;
  public static final int IMPRI = 44;
  public static final int MULTI = 15;
  public static final int PARC = 12;
  public static final int PARA = 41;
  public static final int A_TXT = 35;
  public static final int TD_NUMBER = 8;
  public static final int MODIF = 49;
  public static final int MAY = 24;
  public static final int LLAVEC = 31;
  public static final int LLAVEA = 30;
  public static final int VAR = 2;
}

